### ISSUE TITLE
Request: sortable tables

### ISSUE THREAD

**Issue by madeddie** [mkuchin/docker-registry-web#32] opened 2016-04-15 14:59 UTC
Not really at home in Grails, but would it be a lot of work to allow sorting tables on columns?

I'd very much like to sort on `Created` of image for instance, also `Size` and on the repositories list on `Tags`.

**Comment by liyaka** [comment] 2016-04-17 11:27
+1

**Comment by madeddie** [comment] 2016-04-17 14:26
The current design does server-side generation of the tables. There is a sortableColumn tag for Grails, but I'm guessing it would be quite inefficient to use that, seeing that the page would have to completely reload all data (and therefor go through all tags again, unless there's some caching going on).

The best way I see for this to work is to move the table generation to the client in javascript. Do you think that'd be a viable plan? If so I can put some time in getting some PoC together.

**Comment by mkuchin** [comment] 2016-04-18 03:16
I'd added basic client side table ordering to the tags page.
It available on docker hub as latest version.  
@madeddie and @liyaka can you check if this implementation satisfy your needs?

**Comment by liyaka** [comment] 2016-04-18 05:58
works fine - thanks!

**Comment by madeddie** [comment] 2016-04-18 09:17
Looks good, awesome!
The `Created` column doesn't sort logically yet though. Maybe you could make it use epoch (seconds since 1970) for that?

**Comment by mkuchin** [comment] 2016-04-18 09:28
What's the problem?
I'm using string representation of date in `td` `data-sort` attribute.
`<td data-sort="2016-04-17T05:34:55"> ... 1 day ago</td>`

**Comment by madeddie** [comment] 2016-04-18 09:36
I'm not sure how the sorting is using this string, but it doesn't understand natural sorting of it.
See
![screenshot 2016-04-18 11 29 35](https://cloud.githubusercontent.com/assets/140660/14599776/9cf478fa-0559-11e6-8e88-84911ed38c52.png)

**Comment by mkuchin** [comment] 2016-04-18 11:58
Thanks for screenshot. That looks strange, I can't reproduce it in my environment. 
I've changed `data-sort` attribute value to unix time. 
Can you check if it working for you in latest version?

**Comment by madeddie** [comment] 2016-04-19 07:02
😳  I ehm, have a plugin that allows me to sort tables in chrome... so... after disabling it, the unix timestamp works fine.
Possibly (probably?) this caused the weirdness with the string-based sort as well.

**Comment by mkuchin** [comment] 2016-04-19 07:46
Thanks for update, closing issue.

**Closed by mkuchin** 2016-04-19 07:46 UTC
