### ISSUE TITLE
Size column in Tags list view always 0

### ISSUE THREAD

**Issue by madeddie** [mkuchin/docker-registry-web#31] opened 2016-04-15 13:46 UTC
When viewing the list of tags of a certain image, the `Size` column always shows `0 bytes`.

If I click through to a specific tags' `Image history` the bottom of the page does show the correct `Total size`.

Running hyper/docker-registry-web:v0.0.2 and distribution/registry:2.4.0

**Comment by madeddie** [comment] 2016-04-15 14:41
My Java (and especially Groovy) is really weak, but, the tags list view determines the blob size(s) with:

`restService.headLength("${name}/blobs/${digest}") ?: 0`

the image details view uses:

`entry.Size ?: restService.headLength("${name}/blobs/${blobs[i]}")`
(`entry` being an entry of the list of `history.v1Compatibility`)

Meaning that if the headLength fails for whatever reason, one returns 0, but the other uses the `Size` field from the `history.v1Compatibility` json strings. I have a feeling it would be prudent to make both use the same method, either fixing a possible problem in a comparable fashion in one or for forcing a possible bug in the other.

**Comment by mkuchin** [comment] 2016-04-17 04:07
Thank for bug report, @madeddie.
The problem is `entry.Size`  used only for compatibility with images created in docker engine version < 1.10. It seems working in you case but should no longer work with freshly generated images. 
What registry storage backend are you using?

**Comment by mkuchin** [comment] 2016-04-17 06:25
Can you check if problem fixed in latest version?

**Comment by madeddie** [comment] 2016-04-17 13:49
Yes, the sizes are there now. The loading of the tags list is somewhat slower, so I assume it actually does something it didn't do before :)

We're using the s3 backend.
We host quite some older images from around docker engine 1.6, so that would explain why the v1comp stuff still worked :)

**Closed** 2016-04-19 04:05 UTC
